service: fashion-service

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  memorySize: 512

functions:
  fashionFunc:
    handler: index.handler
    events:
      - http:
          path: fashion
          method: get
      - http:
          path: fashion/{id}
          method: get
      - http:
          path: fashion
          method: post
      - http:
          path: fashion/{id}
          method: put
      - http:
          path: fashion/{id}
          method: delete

plugins:
  - serverless-offline
